# Generated by Django 2.0.5 on 2018-05-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20180509_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.IntegerField(default=0),
        ),
    ]
