# Generated by Django 2.0.3 on 2018-05-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('nickname', models.CharField(default='暂时没有名字的商品', max_length=32)),
                ('description', models.TextField(default='暂无说明')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripition', models.CharField(default='商品照片', max_length=32)),
                ('url', models.URLField(default='/static/images/no_image.png')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Goods')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='BoundPayment',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='goods',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Profile'),
        ),
    ]
