# Generated by Django 2.0.3 on 2018-05-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180506_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(default='暂无说明')),
                ('website', models.URLField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripition', models.CharField(default='商品照片', max_length=32)),
                ('url', models.URLField(default='/static/images/no_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='goodsphoto',
            name='goods',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsPhoto',
        ),
    ]
