# Generated by Django 2.0.3 on 2018-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180506_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
