# Generated by Django 2.0.3 on 2018-05-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20180506_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='website',
        ),
    ]
