# Generated by Django 2.0.5 on 2018-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_remove_product_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
