# Generated by Django 2.0.5 on 2018-05-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='male',
            field=models.IntegerField(default=0),
        ),
    ]
