# Generated by Django 2.0.5 on 2018-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20180512_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbindingmail',
            name='email',
            field=models.EmailField(default='abc@163.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
