# Generated by Django 2.0.5 on 2018-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20180512_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentbindingmail',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_binding',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pay_binding',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='CurrentBindingMail',
        ),
    ]
