# Generated by Django 2.0.5 on 2018-06-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0022_auto_20180514_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
