# Generated by Django 2.0.5 on 2018-06-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_auto_20180606_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='enabled',
        ),
    ]
