# Generated by Django 2.0.5 on 2018-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_remove_profile_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='暂无简介'),
        ),
    ]
