# Generated by Django 2.0.5 on 2018-05-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180513_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_profile', models.CharField(max_length=256)),
                ('key', models.CharField(max_length=16)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Profile')),
            ],
        ),
    ]
