# Generated by Django 2.0.5 on 2018-05-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180513_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
